name: vader_framework
publish_to: none
environment:
  sdk: ^3.7.0

dev_dependencies:
  melos: ^7.0.0-dev.7

workspace:
  - cli/code_builder
  - cli/design_builder
  - core/vader_app
  #- core/vader_app_info
  - core/vader_console
  - core/vader_core
  - core/vader_design
  - core/vader_server
  #- example_design
  #- example_project
