name: vader_app
description: Framework for simplify development of Flutter apps
repository: https://github.com/mjablecnik/vader_framework/tree/master
resolution: workspace
version: 0.4.0

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #vader_core: any
  #vader_design: any
  vader_core:
    path: ../vader_core
  vader_design:
    path: ../vader_design

  go_router: ^16.2.0
  talker_flutter: ^5.0.0
  back_button_interceptor: ^8.0.4

  app_settings: ^6.1.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  flutter_svg: ^2.2.1

  # State Manager:
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  talker_bloc_logger: ^5.0.0

  # Simple Storage:
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1

  # App Info:
  package_info_plus: ^8.3.1
  device_info_plus: ^11.5.0
  mobile_device_identifier: ^0.0.3


dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.15
