name: vader_app
description: Framework for simplify development of Flutter apps
repository: https://github.com/mjablecnik/vader_framework/tree/master
resolution: workspace
version: 0.3.2

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #vader_core: ^0.4.0
  #vader_design: ^0.2.0
  vader_core:
    path: ../vader_core
  vader_design:
    path: ../vader_design

  go_router: ^16.2.0
  talker_flutter: ^4.6.14
  back_button_interceptor: ^8.0.4

  # State Manager:
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  talker_bloc_logger: ^4.6.14

  # Simple Storage:
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0

  # App Info:
  package_info_plus: ^8.3.1
  mobile_device_identifier: ^0.0.3
  android_device_id_generator: 0.1.1

  # Connection:
  #flutter_offline: 3.0.1
  #simple_connection_checker: ^0.3.4
  #internet_connection_checker: 3.0.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
