name: vader_server
description: Vader package for build cli programs.
repository: https://github.com/mjablecnik/vader_framework/tree/master/core/vader_server
resolution: workspace
version: 0.1.0

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  uuid: ^4.5.1
  serinus: ^1.0.3
  vader_core: ^0.4.2
  hotreloader: ^4.1.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
